BigBoringBlog/urls.py
from django.urls import path
from . import views

app_name = 'BigBoringBlog'  # namespacing your app

urlpatterns = [
    path('', views.Home, name='home'),
    path('topics/<str:p_key>/', views.TopicsPage, name='topics'),
    path('create_topic/<str:p_key>/', views.CreateTopic, name='create_topic'),
    path('comments/<str:p_key>/', views.CommentSection, name='comments'),
    path('about/', views.AboutPage, name='about')
]

BoringDjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('BigBoringBlog.urls')),
]

BigBoringBlog/models.py
from django.db import models

# Create your models here.

class Board(models.Model):
    name = models.CharField(max_length=100, unique=True)
    description = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Topic(models.Model):
    subject = models.CharField(max_length=255)
    board = models.ForeignKey(Board, on_delete=models.CASCADE, related_name='topics') #  But if we don’t set a name for it, Django will generate it with the name: (class_name)_set
    created_by = models.CharField(max_length=100, default='Anonymous')
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.subject

class Post(models.Model):
    message = models.TextField(max_length=4000)
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE, related_name='posts')
    created_by = models.CharField(max_length=100, default='Anonymous')
    created_at = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.message

BigBoringBlog/forms.py
from django.forms import ModelForm

from .models import Topic, Post

class TopicForm(ModelForm):
    class Meta:
        model = Topic
        fields = ['subject', 'created_by']

class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['message', 'created_by']

BigBoringBlog/views.py
from django.shortcuts import render, redirect

# Create your views here.
from .models import *
from .forms import *

# BigBoringBlog
def Home(request):
    # boards = Board.objects.all()
    boards = Board.objects.order_by('name')
    context = {'boards': boards}
    return render(request, 'BigBoringBlog/home.html', context)
    
def TopicsPage(request, p_key):
    board = Board.objects.get(id=p_key)

    topics = board.topics.all().order_by('-created_at')
    context = {'board': board, 'topics': topics}
    return render(request, 'BigBoringBlog/topics.html', context)

def CreateTopic(request, p_key):
    form = TopicForm()
    if request.method == 'POST':
        form = TopicForm(request.POST)
        if form.is_valid():
            topic = form.save(commit=False)
            board = Board.objects.get(id=p_key)
            topic.board = board
            topic.save()
            return redirect('BigBoringBlog:topics', p_key=p_key)

    context = {'form':form}
    return render(request, 'BigBoringBlog/create_topic.html', context)

def CommentSection(request, p_key):
    topic = Topic.objects.get(id=p_key)

    form = PostForm()
    if request.method == 'POST':
        form = PostForm(request.POST)
        if form.is_valid():
            post = form.save(commit=False)
            post.topic = topic
            post.save()
            form = PostForm()

    posts = topic.posts.all().order_by('-created_at')
    context = {'topic': topic, 'posts': posts, 'form': form}
    return render(request, 'BigBoringBlog/posts.html', context)

def AboutPage(request):
    return render(request, 'BigBoringBlog/about.html')

BigBoringBlog/templates/BigBoringBlog/about.html
{% extends 'BigBoringBlog/main.html' %}

{% block content %}
<div class="about">
    <h1>This site was made by SUHAS.K.SHETTY [Me] because I was bored</h1>
    <hr>
    <h2>This site was inspired by www.4chan.org</h2>
    <h2>You are Anonymous or can use any other name</h2>
    <h2>The site is text based only</h2>
    <h2>-[ Special Thanks to my sister Phalguni.K.Shetty ]-</h2>
    <br><br><br>
    <a href="https://github.com/DarkSchokolade"><h3>Github</h3></a>
    <a href="https://www.linkedin.com/in/suhas-k-shetty-23b76619b/"><h3>Linkedin</h3></a>
</div>


{% endblock %}

BigBoringBlog/templates/BigBoringBlog/create_topic.html
{% extends 'BigBoringBlog/main.html' %}

{% block content %}

<form action="" method="post" autocomplete="off">
    {% csrf_token %}
    {{ form }}
    <button class="post-btn" type="submit">Post!</button>
</form>

{% endblock %}

BigBoringBlog/templates/BigBoringBlog/home.html
{% extends 'BigBoringBlog/main.html' %}

{% block content %}

<section class="basic-grid" style="margin-left: 23px; margin-right: 23px;">
{% for board in boards %}
    <a href="{% url 'BigBoringBlog:topics' board.id %}">
        <div class="card">
            <div class="content">
                <h1>{{ board }}</h1>
                <hr>
                <p>{{ board.description }}</p>
            </div>
        </div>
    </a>

{% endfor %}
</section>

{% endblock %}

BigBoringBlog/templates/BigBoringBlog/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BigBoringBlog</title>

    <style>
        @import url("{% static 'BigBoringBlog/css/style.css' %}");
        @import url("{% static 'BigBoringBlog/css/card.css' %}");
    </style>
</head>
<body>
    {% include 'BigBoringBlog/nav.html' %}
    {% block content %}

    {% endblock content %}

    <div class="footer">
        <h3>BigBoringBlog <sub>by suhas.k.shetty</sub></h3>
    </div>
</body>
</html>

BigBoringBlog/templates/BigBoringBlog/nav.html
{% load static %}

<style>
    @import url("{% static 'BigBoringBlog/css/nav.css' %}");
</style>

<nav>
    <div class="logo">
        <h3>BigBoringBlog</h3>
    </div>
    <ul class="nav-links">
        <li>
            <a href="{% url 'BigBoringBlog:home' %}">Home</a>
        </li>
        <li>
            <a href="{% url 'BigBoringBlog:about' %}">About</a>
        </li>
    </ul>
</nav>

BigBoringBlog/templates/BigBoringBlog/posts.html
{% extends 'BigBoringBlog/main.html' %}

{% block content %}

<div class="center">
    <h1>Comments</h1>
</div>

<form action="" method="post" autocomplete="off">
    {% csrf_token %}
    {{ form.as_p}}
    <button class="post-btn" type="submit">POST IT!</button>
</form>

<section class="basic-grid" style="margin-left: 23px; margin-right: 23px;">
{% for post in posts %}
    <div class="card">
        <div class="content">
            <h2>{{ post }}</h2>
            <hr>
            <p>By: {{ post.created_by }}</p>
            <p>On: {{ post.created_at }}</p>
        </div>
    </div>
{% endfor %}
</section>

{% endblock %}

BigBoringBlog/templates/BigBoringBlog/topics.html
{% extends 'BigBoringBlog/main.html' %}

{% block content %}

<div class="center">
    <a href="{% url 'BigBoringBlog:create_topic' board.id %}"><button class="create-btn">Create a topic</button></a>
</div>

<section class="basic-grid" style="margin-left: 23px; margin-right: 23px;">
{% for topic in topics %}
    <a href="{% url 'BigBoringBlog:comments' topic.id %}">
        <div class="card">
            <div class="content">
                <h1>{{ topic }}</h1>
                <hr>
                <p>By: {{ topic.created_by }}</p>
                <p>On: {{ topic.created_at }}</p>
                <p>Comments >></p>
            </div> 
        </div>
    </a>
    
{% endfor %}
</section>

{% endblock %}